import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBarRols from "@/components/NavBarRols";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navigation = [
    { name: "Inicio", href: "/inicio", current: false },
    { name: "Perfil", href: "/perfil", current: false },
    { name: "Entidades Autorizadas", href: "/autorizaciones", current: false },
    { name: "Notificaciones", href: "/notificaciones", current: false },
    { name: "Métricas", href: "/metricas", current: false },
    { name: "Cerrar Sesión", href: "/logout", current: false },
  ];
  return (
    <html lang="en">
      <body className={"bg-gray-100"}>
        <NavBarRols navigation={navigation} />
        {children}
      </body>
    </html>
  );
}
