
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import SessionAuthProvider from "@/context/SessionProvider";
import { AuroraBackground } from "@/components/ui/aurora-background";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SysProgestion",
  /*description: "Generated by create next app",*/
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"bg-gray-100"}>
        <SessionAuthProvider>
          <NavBar />
          <AuroraBackground>
          <div className=" w-[100vw] min-h-[80vh]">
            {children}
          </div>
          </AuroraBackground>
        </SessionAuthProvider>
        <Footer />
      </body>
    </html>
  );
}
